# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LicenseService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14LicenseService.proto\x12\x10\x63om.example.grpc\"E\n\x13LicensePlateRequest\x12\x14\n\x0cPlateRequest\x18\x01 \x01(\t\x12\x18\n\x10PlateListRequest\x18\x02 \x03(\t\"-\n\x14LicensePlateResponse\x12\x15\n\rPlateResponse\x18\x01 \x01(\t2p\n\x13LicensePlateService\x12Y\n\x08greeting\x12%.com.example.grpc.LicensePlateRequest\x1a&.com.example.grpc.LicensePlateResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LicenseService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LICENSEPLATEREQUEST._serialized_start=42
  _LICENSEPLATEREQUEST._serialized_end=111
  _LICENSEPLATERESPONSE._serialized_start=113
  _LICENSEPLATERESPONSE._serialized_end=158
  _LICENSEPLATESERVICE._serialized_start=160
  _LICENSEPLATESERVICE._serialized_end=272
# @@protoc_insertion_point(module_scope)
